import { StylingResult } from "./schema";

export const MOCK_RESULT: StylingResult = {
  room_reading:
    "A plain bedroom with white walls, a bed with basic sheets, and minimal furniture. The space feels cold and impersonal — no art on the walls, no plants, no warm lighting, and the floor is bare hardwood.",
  style_direction:
    "Warm Scandinavian cozy — layered textiles, warm lighting, organic textures, and personal touches to create an inviting retreat.",
  items: [
    {
      name: "Warm White Fairy String Lights (33ft)",
      category: "lighting",
      estimated_price: 12,
      priority: 1,
      suggested_store: "Amazon",
      reason: "The room has only harsh overhead lighting. Draping warm string lights above the headboard or along the wall instantly transforms the mood.",
      placement_x: 50,
      placement_y: 15,
    },
    {
      name: "Chunky Knit Throw Blanket",
      category: "textiles",
      estimated_price: 25,
      priority: 2,
      suggested_store: "Target",
      reason: "The bed looks flat and uninviting. A textured throw draped at the foot adds warmth, depth, and a cozy focal point.",
      placement_x: 50,
      placement_y: 60,
    },
    {
      name: "Set of 3 Black Gallery Frames (8x10)",
      category: "wall_decor",
      estimated_price: 15,
      priority: 3,
      suggested_store: "IKEA",
      reason: "The wall above the bed is completely bare. A small gallery cluster fills the emptiness and adds personality.",
      placement_x: 50,
      placement_y: 25,
    },
    {
      name: "Velvet Accent Pillow Covers (2-pack)",
      category: "textiles",
      estimated_price: 12,
      priority: 4,
      suggested_store: "Amazon",
      reason: "No decorative pillows visible. Textured velvet in a warm tone layers depth onto the bed and complements the throw.",
      placement_x: 45,
      placement_y: 48,
    },
    {
      name: "Faux Pothos Trailing Plant in Ceramic Pot",
      category: "plants",
      estimated_price: 14,
      priority: 5,
      suggested_store: "IKEA",
      reason: "No greenery anywhere. A trailing plant on a shelf or nightstand brings life and organic texture.",
      placement_x: 85,
      placement_y: 55,
    },
    {
      name: "Ceramic Table Lamp with Linen Shade",
      category: "lighting",
      estimated_price: 22,
      priority: 6,
      suggested_store: "Target",
      reason: "No bedside lighting. A warm-toned lamp on the nightstand provides task lighting and ambient glow.",
      placement_x: 15,
      placement_y: 50,
    },
    {
      name: "Woven Jute Area Rug (3x5 ft)",
      category: "textiles",
      estimated_price: 28,
      priority: 7,
      suggested_store: "Amazon",
      reason: "Bare hardwood floor beside the bed feels cold. A natural-fiber rug adds warmth underfoot and visual grounding.",
      placement_x: 50,
      placement_y: 80,
    },
    {
      name: "Wooden Decorative Tray",
      category: "accessories",
      estimated_price: 10,
      priority: 8,
      suggested_store: "HomeGoods",
      reason: "Nightstand surface looks cluttered or empty. A tray corrals items into an intentional vignette.",
      placement_x: 15,
      placement_y: 60,
    },
    {
      name: "Flameless LED Candle Set (3-pack)",
      category: "accessories",
      estimated_price: 12,
      priority: 9,
      suggested_store: "Amazon",
      reason: "Adding candle glow on the tray or shelf creates a warm, inviting ambiance without fire risk.",
      placement_x: 20,
      placement_y: 55,
    },
    {
      name: "Round Rattan Wall Mirror (18 inch)",
      category: "wall_decor",
      estimated_price: 20,
      priority: 10,
      suggested_store: "Target",
      reason: "A textured mirror on the opposite wall reflects light and makes the small room feel larger.",
      placement_x: 80,
      placement_y: 30,
    },
  ],
  buy_order: [
    "Warm White Fairy String Lights (33ft)",
    "Chunky Knit Throw Blanket",
    "Set of 3 Black Gallery Frames (8x10)",
    "Velvet Accent Pillow Covers (2-pack)",
    "Faux Pothos Trailing Plant in Ceramic Pot",
    "Ceramic Table Lamp with Linen Shade",
    "Woven Jute Area Rug (3x5 ft)",
    "Wooden Decorative Tray",
    "Flameless LED Candle Set (3-pack)",
    "Round Rattan Wall Mirror (18 inch)",
  ],
  total_estimated_cost: 170,
};
